export const appsStr = {
  title: '应用',
  subtitle: '配置的归属单元，客户端 SDK 凭 AppId 与 Secret 拉取配置',
  searchPlaceholder: '搜索应用名 / AppId…',
  groupAll: '全部分组',
  create: '新建应用',
  emptyTitle: '还没有应用',
  emptyAction: '创建第一个应用',
  count: (n: number) => `共 ${n} 个应用`,
  badges: {
    enabled: '已启用',
    disabled: '已禁用',
    shared: '公共应用',
    inherits: (names: string[]) => `继承 ${names.join('、')}`,
  },
  table: {
    name: '应用',
    appId: 'AppId',
    group: '分组',
    status: '状态',
    inherit: '继承关系',
    updateTime: '更新时间',
    actions: '操作',
    noGroup: '未分组',
  },
  actions: {
    configs: '配置',
    edit: '编辑',
    disable: '禁用',
    enable: '启用',
    delete: '删除',
    secret: 'Secret',
    copySecret: '复制 Secret',
    copyAppId: '复制 AppId',
    copied: '已复制',
  },
  dialog: {
    createTitle: '新建应用',
    editTitle: '编辑应用',
    name: '应用名称',
    namePlaceholder: '例如：订单服务',
    appId: 'AppId',
    appIdHint: '已自动生成，可修改；创建后不可变',
    group: '分组',
    groupPlaceholder: '例如：交易线（可选）',
    enabled: '启用应用',
    inheritanced: '作为公共应用（供其他应用继承配置）',
    inheritancedApps: '继承的应用',
    inheritancedAppsHint: '本应用将自动获得所选应用的配置，同名 key 可覆盖',
    inheritancedAppsEmpty: '暂无可继承的公共应用',
    submit: '创建',
    submitting: '创建中…',
    save: '保存',
    saving: '保存中…',
  },
  confirm: {
    deleteTitle: '删除应用',
    deleteBody: (name: string) =>
      `将删除应用「${name}」及其全部配置与发布历史，此操作不可恢复。确定删除？`,
    disableTitle: '禁用应用',
    disableBody: (name: string) => `禁用后客户端将无法拉取「${name}」的配置。确定禁用？`,
    enableTitle: '启用应用',
    enableBody: (name: string) => `启用后客户端恢复拉取「${name}」的配置。确定启用？`,
  },
  errors: {
    nameRequired: '请输入应用名称',
    appIdRequired: '请输入 AppId',
    appIdInvalid: 'AppId 仅支持字母、数字、中划线、下划线（≤64 位）',
    appNameExists: '应用名已存在',
  },
  secretTitle: '应用凭证',
  secretHint: '客户端 SDK 连接串使用，仅管理员可见',
} as const
