export const configsStr = {
  title: (appName: string) => `${appName} · 配置管理`,
  envSuffix: '当前环境',
  views: { table: '表格', kv: 'KV', json: 'JSON', history: '历史' },
  searchPlaceholder: '过滤键 / 值 / 分组…',
  create: '新建配置',
  batchBar: {
    selected: (n: number) => `已选 ${n} 条`,
    delete: '批量删除',
    cancel: '取消改动',
    clear: '取消选择',
  },
  pendingStrip: {
    label: '待发布改动',
    add: (n: number) => `新增 ${n}`,
    edit: (n: number) => `修改 ${n}`,
    del: (n: number) => `删除 ${n}`,
    publish: '发布…',
    cancelAll: '全部取消',
    none: '当前环境没有待发布改动',
  },
  table: {
    group: '分组',
    key: '键',
    value: '值',
    online: '线上状态',
    pending: '待发布',
    description: '描述',
    updateTime: '更新时间',
    actions: '操作',
    inheritedFrom: (appName: string) => `继承自 ${appName}`,
    showInherited: '显示继承配置（合并视图）',
  },
  badges: {
    online: '已上线',
    offline: '未上线',
    added: '新增',
    edited: '修改',
    deleted: '删除',
  },
  actions: {
    edit: '编辑',
    delete: '删除',
    cancelEdit: '取消改动',
    history: '历史',
  },
  dialog: {
    createTitle: '新建配置',
    editTitle: '编辑配置',
    group: '分组',
    groupPlaceholder: '例如：database（可选）',
    key: '键',
    keyPlaceholder: '例如：timeout_seconds',
    value: '值',
    valuePlaceholder: '支持多行文本',
    description: '描述',
    descriptionPlaceholder: '选填，发布后会以注释形式出现在 JSON 视图',
    submit: '创建',
    submitting: '创建中…',
    save: '保存',
    saving: '保存中…',
  },
  inline: {
    hint: '回车保存 · Esc 取消',
  },
  io: {
    exportJson: '导出 JSON',
    importJson: '导入 JSON',
    syncEnv: '同步到其他环境',
    importTitle: '从 JSON 文件导入配置',
    importHint: '支持带注释的 jsonc；层级键 a:b:c 会拆为分组 a:b + 键 c，注释写入描述',
    importItems: (n: number) => `将新增 ${n} 条配置（导入后处于待发布状态）`,
    importConfirm: '确认导入',
    importing: '导入中…',
    previewEmpty: '文件中没有可导入的配置',
    typeNotesTitle: '类型字面量说明',
    typeNotes: [
      '按标准 JSON 书写：true/false 会被服务端规范化为 True/False 存储，应用端绑定正常',
      'JSON null 会存成空字符串（不是删除该键），不要用 null 表达"关闭"，请写 false',
      '"1"/"0" 不是合法布尔字面量；小数请绑定 double/decimal（int 会报错）',
    ],
    syncTitle: '环境间同步',
    syncHint: (from: string) => `把当前环境 ${from} 的全部配置覆盖到所选目标环境（同名键覆盖、新增键补齐），目标环境将产生待发布改动`,
    syncConfirm: '开始同步',
    syncing: '同步中…',
    noOtherEnv: '没有其他可选环境',
    expandAll: '全部展开',
    collapseAll: '全部收起',
  },
  toasts2: {
    imported: '配置导入成功（待发布）',
    synced: (envs: string) => `已同步到 ${envs}`,
  },
  diffBar: {
    tabs: { online: '与线上差异', unsaved: '未保存修改' },
    summary: (a: number, c: number, r: number) => `+${a} ~${c} -${r}`,
    title: '与已保存版本的差异',
    fullWarning: (n: number) => `全量模式：保存后这 ${n} 个键将被标记"待发布删除"`,
    empty: '与已保存版本一致，没有未保存的修改',
    kinds: { added: '新增', changed: '修改', removed: '将删除' },
  },
  patchTip: [
    '勾选（补丁）：只改文本里出现的键，其他键保持不变',
    '不勾（全量）：文本就是完整目标状态——没出现在文本里的已有键会被标记"待发布删除"，发布后从客户端移除',
    '例：库里 a/b/c 三键，文本只写 a=100 → 补丁只改 a；全量则 b、c 进入待发布删除',
  ],
  kv: {
    loadError: 'KV 视图加载失败',
    save: '保存 KV',
    saving: '保存中…',
    patch: '补丁模式（只提交差异）',
    reload: '重新加载',
    dirtyGuardTitle: '放弃未保存的修改？',
  },
  jsonView: {
    loadError: 'JSON 视图加载失败',
    save: '保存 JSON',
    saving: '保存中…',
    patch: '补丁模式（只提交差异）',
    reload: '重新加载',
    editing: '编辑 JSON（含注释，保存后按 key 同步到配置）',
    diffToggle: '对比已保存',
    foldAll: '折叠全部',
    unfoldAll: '展开全部',
  },
  confirm: {
    deleteTitle: '删除配置',
    deleteBody: (key: string) =>
      `将删除配置「${key}」。若该配置已发布，会先进入"待发布删除"，发布后客户端生效；未发布的直接删除。`,
    batchDeleteTitle: '批量删除配置',
    batchDeleteBody: (n: number) =>
      `将删除选中的 ${n} 条配置（已发布的进入待发布删除）。确定继续？`,
    cancelAllTitle: '取消全部待发布改动',
    cancelAllBody: '将撤销所有未发布的修改，恢复到当前线上版本。确定继续？',
    concurrencyTitle: '配置已被他人修改',
    concurrencyBody: (key: string) =>
      `「${key}」在服务端已有更新的修改（updateTime 变化）。覆盖将丢失对方的改动，放弃则保留你的内容重新加载。`,
    concurrencyOverwrite: '覆盖保存',
    concurrencyDiscard: '放弃并刷新',
  },
  empty: {
    title: '还没有配置',
    action: '创建第一条配置',
    noMatch: '没有匹配的配置',
    clearFilter: '清除筛选',
  },
  toasts: {
    created: '配置已创建',
    saved: '配置已保存',
    deleted: '配置已删除',
    batchDeleted: (n: number) => `已删除 ${n} 条配置`,
    editCanceled: '已取消改动',
    allCanceled: '已取消全部待发布改动',
    kvSaved: 'KV 已保存',
    jsonSaved: 'JSON 已保存',
    failed: '操作失败',
  },
  errors: {
    groupRequired: '请输入分组或留空',
    keyRequired: '请输入键',
    keyInvalid: '键不支持冒号（group:key 会与分组解析冲突）',
    valueRequired: '请输入值',
  },
} as const
