export const configsStr = {
  title: (appName: string) => `${appName} · 配置管理`,
  envSuffix: '当前环境',
  views: { table: '表格', kv: 'KV', json: 'JSON' },
  searchPlaceholder: '过滤键 / 值 / 分组…',
  create: '新建配置',
  batchBar: {
    selected: (n: number) => `已选 ${n} 条`,
    delete: '批量删除',
    cancel: '取消改动',
    clear: '取消选择',
  },
  pendingStrip: {
    label: '待发布改动',
    add: (n: number) => `新增 ${n}`,
    edit: (n: number) => `修改 ${n}`,
    del: (n: number) => `删除 ${n}`,
    publish: '发布…',
    cancelAll: '全部取消',
    none: '当前环境没有待发布改动',
  },
  table: {
    group: '分组',
    key: '键',
    value: '值',
    online: '线上状态',
    pending: '待发布',
    description: '描述',
    updateTime: '更新时间',
    actions: '操作',
    inheritedFrom: (appName: string) => `继承自 ${appName}`,
    showInherited: '显示继承配置（合并视图）',
  },
  badges: {
    online: '已上线',
    offline: '未上线',
    added: '新增',
    edited: '修改',
    deleted: '删除',
  },
  actions: {
    edit: '编辑',
    delete: '删除',
    cancelEdit: '取消改动',
    history: '历史',
  },
  dialog: {
    createTitle: '新建配置',
    editTitle: '编辑配置',
    group: '分组',
    groupPlaceholder: '例如：database（可选）',
    key: '键',
    keyPlaceholder: '例如：timeout_seconds',
    value: '值',
    valuePlaceholder: '支持多行文本',
    description: '描述',
    descriptionPlaceholder: '选填，发布后会以注释形式出现在 JSON 视图',
    submit: '创建',
    submitting: '创建中…',
    save: '保存',
    saving: '保存中…',
  },
  inline: {
    hint: '回车保存 · Esc 取消',
  },
  kv: {
    loadError: 'KV 视图加载失败',
    save: '保存 KV',
    saving: '保存中…',
    patch: '补丁模式（只提交差异）',
    reload: '重新加载',
    dirtyGuardTitle: '放弃未保存的修改？',
  },
  jsonView: {
    loadError: 'JSON 视图加载失败',
    save: '保存 JSON',
    saving: '保存中…',
    patch: '补丁模式（只提交差异）',
    reload: '重新加载',
    editing: '编辑 JSON（含注释，保存后按 key 同步到配置）',
  },
  confirm: {
    deleteTitle: '删除配置',
    deleteBody: (key: string) =>
      `将删除配置「${key}」。若该配置已发布，会先进入"待发布删除"，发布后客户端生效；未发布的直接删除。`,
    batchDeleteTitle: '批量删除配置',
    batchDeleteBody: (n: number) => `将删除选中的 ${n} 条配置（已发布的进入待发布删除）。确定继续？`,
    cancelAllTitle: '取消全部待发布改动',
    cancelAllBody: '将撤销所有未发布的修改，恢复到当前线上版本。确定继续？',
    concurrencyTitle: '配置已被他人修改',
    concurrencyBody: (key: string) =>
      `「${key}」在服务端已有更新的修改（updateTime 变化）。覆盖将丢失对方的改动，放弃则保留你的内容重新加载。`,
    concurrencyOverwrite: '覆盖保存',
    concurrencyDiscard: '放弃并刷新',
  },
  empty: {
    title: '还没有配置',
    action: '创建第一条配置',
    noMatch: '没有匹配的配置',
    clearFilter: '清除筛选',
  },
  toasts: {
    created: '配置已创建',
    saved: '配置已保存',
    deleted: '配置已删除',
    batchDeleted: (n: number) => `已删除 ${n} 条配置`,
    editCanceled: '已取消改动',
    allCanceled: '已取消全部待发布改动',
    kvSaved: 'KV 已保存',
    jsonSaved: 'JSON 已保存',
    failed: '操作失败',
  },
  errors: {
    groupRequired: '请输入分组或留空',
    keyRequired: '请输入键',
    keyInvalid: '键不支持冒号（group:key 会与分组解析冲突）',
    valueRequired: '请输入值',
  },
} as const
