/** 角色管理页文案（ITER-07；仅中文，见 handoff §9） */
export const rolesStr = {
  title: '角色管理',
  subtitle: '角色是权限码的集合，用户可同时持有多个角色',
  create: '新建角色',
  count: (n: number) => `共 ${n} 个角色`,
  emptyTitle: '还没有角色',
  emptyAction: '创建第一个角色',
  loadFailed: '加载失败',
  retry: '重试',
  table: {
    name: '角色名',
    description: '描述',
    type: '类型',
    permissions: '权限数',
    actions: '操作',
  },
  badges: {
    system: '系统角色',
    custom: '自定义',
  },
  permCount: (n: number) => `${n} 项`,
  actions: {
    edit: '编辑',
    delete: '删除',
  },
  dialog: {
    createTitle: '新建角色',
    editTitle: '编辑角色',
    name: '角色名称',
    namePlaceholder: '例如：只读运维',
    description: '描述',
    descriptionPlaceholder: '用途说明（可选）',
    permissions: '权限',
    selectedCount: (n: number) => `已选 ${n} 项`,
    groupCount: (n: number, m: number) => `${n}/${m}`,
    permissionsLoading: '加载中…',
    permissionsFailed: '权限清单加载失败',
    permissionsEmpty: '暂无权限码',
    cancel: '取消',
    submit: '创建',
    submitting: '创建中…',
    save: '保存',
    saving: '保存中…',
  },
  confirm: {
    deleteTitle: '删除角色',
    deleteBody: (name: string) =>
      `将删除角色「${name}」，持有该角色的用户将立即失去对应权限，此操作不可恢复。确定删除？`,
  },
  toasts: {
    created: (name: string) => `角色「${name}」已创建`,
    saved: (name: string) => `角色「${name}」已保存`,
    deleted: (name: string) => `角色「${name}」已删除`,
    failed: '操作失败',
  },
  errors: {
    nameRequired: '请输入角色名称',
    nameMax: '角色名称不能超过 128 个字符',
    descriptionMax: '描述不能超过 512 个字符',
    saveFailed: '保存失败',
  },
  /** 权限码域中文名（键 = 下划线前缀；清单以 SupportedPermissions 返回为准） */
  domainNames: {
    APP: '应用',
    CONFIG: '配置',
    NODE: '节点',
    CLIENT: '客户端',
    USER: '用户',
    ROLE: '角色',
    SERVICE: '服务',
    LOG: '日志',
  },
  otherDomain: '其他',
} as const
