export const servicesStr = {
  title: '服务注册中心',
  subtitle: '业务服务实例向 AgileConfig 注册与发现',
  add: '手动注册',
  searchNamePlaceholder: '按服务名过滤…',
  searchIdPlaceholder: '按服务 ID 过滤…',
  statusLabel: '健康状态',
  statusAll: '全部状态',
  count: (n: number) => `共 ${n} 个服务`,
  loadFailed: '加载失败',
  noMatchTitle: '没有匹配的服务',
  clearFilter: '清除筛选',
  emptyTitle: '还没有注册的服务',
  emptyHint: '服务通过客户端 SDK 自动注册，也可在此手动注册',
  emptyAction: '注册第一个服务',
  table: {
    name: '服务名',
    serviceId: '服务ID',
    instance: '实例',
    status: '状态',
    heartBeatMode: '心跳方式',
    registerTime: '注册时间',
    lastHeartBeat: '最后心跳',
    actions: '操作',
  },
  badges: {
    healthy: '健康',
    unhealthy: '不健康',
  },
  heartBeat: {
    url: 'URL 探活',
    tcp: 'TCP 探活',
  },
  actions: {
    remove: '移除',
  },
  dialog: {
    title: '手动注册服务',
    serviceId: '服务ID',
    serviceIdPlaceholder: '例如：order-service',
    serviceName: '服务名',
    serviceNamePlaceholder: '例如：订单服务',
    ip: 'IP',
    ipPlaceholder: '例如：192.168.0.21（选填）',
    port: '端口',
    portPlaceholder: '例如：8080（选填）',
    heartBeatMode: '心跳方式',
    heartBeatModeHint: 'url：按检查 URL 探活；tcp：直连 IP:端口探活',
    checkUrl: '检查 URL',
    checkUrlPlaceholder: '例如：http://192.168.0.21:8080/health（选填）',
    alarmUrl: '告警 URL',
    alarmUrlPlaceholder: '服务不健康时回调的地址（选填）',
    submit: '注册',
    submitting: '注册中…',
  },
  confirm: {
    removeTitle: '移除服务',
    removeBody: (name: string) =>
      `将移除服务 ${name}。服务下线后需重新注册才能恢复发现。确定移除？`,
  },
  errors: {
    serviceIdRequired: '请输入服务ID',
    serviceNameRequired: '请输入服务名',
    portInvalid: '端口需为 1–65535 的整数',
  },
  toasts: {
    added: (name: string) => `服务 ${name} 已注册`,
    removed: (name: string) => `服务 ${name} 已移除`,
    failed: '操作失败',
  },
} as const
