export const usersStr = {
  title: '用户管理',
  subtitle: '管理员账号与角色分配',
  searchPlaceholder: '搜索用户名…',
  create: '新建用户',
  noMatchTitle: '没有匹配的用户',
  clearFilter: '清除筛选',
  emptyTitle: '还没有用户',
  emptyAction: '创建第一个用户',
  count: (n: number) => `共 ${n} 个用户`,
  loadFailed: '加载失败',
  retry: '重试',
  table: {
    userName: '用户名',
    team: '团队',
    roles: '角色',
    actions: '操作',
  },
  actions: {
    edit: '编辑',
    resetPassword: '重置密码',
    delete: '删除',
  },
  dialog: {
    createTitle: '新建用户',
    editTitle: '编辑用户',
    userName: '用户名',
    userNamePlaceholder: '例如：zhangsan',
    userNameHint: '创建后不可修改',
    password: '初始密码',
    passwordPlaceholder: '至少 6 位',
    team: '团队',
    teamPlaceholder: '例如：平台组（可选）',
    roles: '角色',
    rolesHint: '勾选该用户担任的角色，决定其可执行的操作',
    rolesEmpty: '暂无可选角色',
    rolesLoading: '加载中…',
    submit: '创建',
    submitting: '创建中…',
    save: '保存',
    saving: '保存中…',
    cancel: '取消',
  },
  confirm: {
    deleteTitle: '删除用户',
    deleteBody: (name: string) =>
      `将删除用户「${name}」，删除后该账号将无法登录，此操作不可恢复。确定删除？`,
    resetTitle: '重置密码',
    resetBody: (name: string) =>
      `将把用户「${name}」的密码重置为服务端默认密码 123456，原密码立即失效。请通知用户登录后尽快修改密码。确定重置？`,
  },
  errors: {
    userNameRequired: '请输入用户名',
    passwordRequired: '请输入初始密码',
    passwordMin: '初始密码至少 6 位',
    saveFailed: '保存失败',
  },
  toasts: {
    created: (name: string) => `用户「${name}」已创建`,
    saved: (name: string) => `用户「${name}」已保存`,
    deleted: (name: string) => `用户「${name}」已删除`,
    passwordReset: '密码已重置为默认密码 123456，请通知用户登录后尽快修改',
    failed: '操作失败',
  },
} as const
